# Notebook for cleaning dataset

In [1]:
import pandas as pd

C:\Users\inesr\AppData\Local\Temp\ipykernel_8424\4080736814.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
data = pd.read_csv('digitals_projects_tracker.csv')
data.head()

,Projet,Statut,Début,Fin prévue,Fin réelle,Budget prévu,Budget réel,Satisfaction client,Risque (%),Délai (jours),Temps passé (jours),Personnes/jours (Effort),Responsable,Département
0,eBanking V1,En cours,2023-01-15,2024-01-15,NaN,1000000,850000.0,85.0,20,365,633,807,Jean Dupont,eBanking
1,Mobile App V2,Terminé,2022-05-10,2023-05-10,2023-05-12,800000,900000.0,90.0,30,370,367,1227,Marie Martin,Mobile Banking
2,eBanking V2,En attente,2024-02-01,2025-02-01,NaN,1200000,NaN,NaN,15,365,251,1247,Sophie Leclerc,Conformité
3,MIS Upgrade,En cours,2023-03-20,2024-03-20,NaN,500000,350000.0,75.0,25,365,569,1274,Paul Durand,Front Office
4,Conformité 3,Terminé,2021-11-01,2022-11-01,2022-10-25,450000,400000.0,80.0,10,350,358,1482,Alice Bernard,MIS

In [3]:
print(data.columns)

Index(['Projet', 'Statut', 'Début', 'Fin prévue', 'Fin réelle', 'Budget prévu',
       'Budget réel', 'Satisfaction client', 'Risque (%)', 'Délai (jours)',
       'Temps passé (jours)', 'Personnes/jours (Effort)', 'Responsable',
       'Département'],
      dtype='object')

In [4]:
print(data.shape)

(15, 14)

In [5]:
# Missing values 
missing_values = data.isnull().sum()
missing_values

Projet                       0
Statut                       0
Début                        0
Fin prévue                   0
Fin réelle                  10
Budget prévu                 0
Budget réel                  5
Satisfaction client          5
Risque (%)                   0
Délai (jours)                0
Temps passé (jours)          0
Personnes/jours (Effort)     0
Responsable                  0
Département                  0
dtype: int64

In [6]:
# Adding the column FTE (Personnes/jours // 220) ==> the number of working days 
data['FTE'] = data['Personnes/jours (Effort)'] / 220
data.head()

,Projet,Statut,Début,Fin prévue,Fin réelle,Budget prévu,Budget réel,Satisfaction client,Risque (%),Délai (jours),Temps passé (jours),Personnes/jours (Effort),Responsable,Département,FTE
0,eBanking V1,En cours,2023-01-15,2024-01-15,NaN,1000000,850000.0,85.0,20,365,633,807,Jean Dupont,eBanking,3.668182
1,Mobile App V2,Terminé,2022-05-10,2023-05-10,2023-05-12,800000,900000.0,90.0,30,370,367,1227,Marie Martin,Mobile Banking,5.577273
2,eBanking V2,En attente,2024-02-01,2025-02-01,NaN,1200000,NaN,NaN,15,365,251,1247,Sophie Leclerc,Conformité,5.668182
3,MIS Upgrade,En cours,2023-03-20,2024-03-20,NaN,500000,350000.0,75.0,25,365,569,1274,Paul Durand,Front Office,5.790909
4,Conformité 3,Terminé,2021-11-01,2022-11-01,2022-10-25,450000,400000.0,80.0,10,350,358,1482,Alice Bernard,MIS,6.736364

In [19]:
# Save as an excel file
data.to_csv('digitals_projects_tracker.csv', index = False)